version: "3.8"

services:
  traefik:
    image: traefik:v2.3.1
    ports:
      - "80:80"
      - "443:443"
    networks:
      - varfish
    restart: unless-stopped
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  varfish-web:
    image: ghcr.io/bihealth/varfish-server:219-genomebuild-field-0
    env_file:
      - .env
    networks:
      - varfish
    restart: unless-stopped
#    volumes:
#      - "/root/varfish-server-background-db-20210728-grch38:/data:ro"
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.xforward.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.routers.varfish-web.entrypoints=web,websecure"
      - "traefik.http.routers.varfish-web.middlewares=xforward"
      - "traefik.http.routers.varfish-web.rule=HostRegexp(`{catchall:.+}`)"
      - "traefik.http.services.varfish-web.loadbalancer.server.port=8080"
      - "traefik.http.routers.varfish-web.tls=true"

  varfish-celerybeat:
    image: ghcr.io/bihealth/varfish-server:219-genomebuild-field-0
    env_file:
      - .env
    command: ["celerybeat"]
    networks:
      - varfish
    depends_on:
      - varfish-web
    restart: unless-stopped

  varfish-celeryd-default:
    image: ghcr.io/bihealth/varfish-server:219-genomebuild-field-0
    env_file:
      - .env
    command: ["celeryd"]
    environment:
      - CELERY_QUEUES=default
      - CELERY_WORKERS=16
    depends_on:
      - varfish-web
    networks:
      - varfish
    restart: unless-stopped

  varfish-celeryd-query:
    image: ghcr.io/bihealth/varfish-server:219-genomebuild-field-0
    env_file:
      - .env
    command: ["celeryd"]
    environment:
      - CELERY_QUEUES=query
      - CELERY_WORKERS=16
    depends_on:
      - varfish-web
    networks:
      - varfish
    restart: unless-stopped

  varfish-celeryd-export:
    image: ghcr.io/bihealth/varfish-server:219-genomebuild-field-0
    env_file:
      - .env
    command: ["celeryd"]
    environment:
      - CELERY_QUEUES=export
      - CELERY_WORKERS=8
    depends_on:
      - varfish-web
    networks:
      - varfish
    restart: unless-stopped

  varfish-celeryd-import:
    image: ghcr.io/bihealth/varfish-server:219-genomebuild-field-0
    env_file:
      - .env
    command: ["celeryd"]
    environment:
      - CELERY_QUEUES=import
      - CELERY_WORKERS=4
    depends_on:
      - varfish-web
    networks:
      - varfish
    restart: unless-stopped

  varfish-celeryd-maintenance:
    image: ghcr.io/bihealth/varfish-server:219-genomebuild-field-0
    env_file:
      - .env
    command: ["celeryd"]
    environment:
      - CELERY_QUEUES=maintenance
      - CELERY_WORKERS=8
    depends_on:
      - varfish-web
    networks:
      - varfish
    restart: unless-stopped

  jannovar:
    image: quay.io/biocontainers/jannovar-cli:0.35--hdfd78af_1
    command: [
        "jannovar", "-Xmx6G", "-Xms2G",
        "rest-server", "--host", "0.0.0.0", "--port", "80",
        "-d", "/data/hg19_ensembl.ser",
        "-d", "/data/hg19_refseq.ser",
        "-d", "/data/hg19_refseq_curated.ser",
        "-d", "/data/hg38_ensembl.ser",
        "-d", "/data/hg38_refseq.ser",
        "-d", "/data/hg38_refseq_curated.ser",
    ]
    volumes:
      - type: bind
        source: ./volumes/jannovar
        target: /data
        read_only: true
    networks:
      - varfish
    restart: unless-stopped

  exomiser-rest-prioritiser:
    image: quay.io/biocontainers/exomiser-rest-prioritiser:12.1.0--1
    command: [
        "exomiser-rest-prioritiser", "-Xmx6G", "-Xms2G", "-Dserver.address=0.0.0.0",
        "-Dserver.port=80",
    ]
    volumes:
      - type: bind
        source: ./config/exomiser/application.properties
        target: /application.properties
        read_only: true
      - type: bind
        source: ./volumes/exomiser
        target: /data
        read_only: true
    networks:
      - varfish
    restart: unless-stopped

  minio:  # minio does not like being tagged
    image: minio/minio
    env_file:
      - .env
    command: ["server", "/data"]
    volumes:
      - type: bind
        source: ./volumes/minio
        target: /data
    networks:
      - varfish
    restart: unless-stopped

  postgres:
    image: postgres:12
    shm_size: 1g
    env_file:
      - .env
    networks:
      - varfish
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./volumes/postgres/data
        target: /var/lib/postgresql/data

  redis:
    image: redis:6
    networks:
      - varfish
    restart: unless-stopped
    volumes:
      - "./volumes/redis/data:/data:rw"

networks:
  varfish:
